(function () {
  window.BtcDash = window.BtcDash || {}; window.BtcDash.chart = window.BtcDash.chart || {}; window.BtcDash.chart.overlays = window.BtcDash.chart.overlays || {};
  function isLayerEnabled(){const s=window.BtcDash.state;return Boolean(s?.chartRuntime?.layerState?.channel||s?.activeLayers?.Channel)}
  function buildChannelOverlayItems(timeframe){const ctx=window.BtcDash.state?.channelContexts?.[timeframe], ch=ctx?.localChannel; if(!ctx?.available||!ch?.available||ch.status==="No Clear Channel")return[]; return [ch.upperZone,ch.midZone,ch.lowerZone].filter(Boolean).map(z=>({layer:"channel",timeframe,source:"Channel",sourceId:`${timeframe}-${z.boundaryType}`,type:z.boundaryType,label:`${timeframe} Channel ${z.boundaryType}`,zoneLow:z.zoneLow,zoneHigh:z.zoneHigh,price:z.centerPrice,startTime:ch.validFromTime,endTime:ch.projectionEndTime||ch.validToTime,drawPolicy:ch.drawPolicy||"show",score:ch.score,status:ch.status}));}
  function clearChannelOverlay(){window.BtcDash.chart.overlays.zone?.clearZoneOverlayLayer?.("channel")}
  function renderChannelOverlay(timeframe){clearChannelOverlay(timeframe); if(!isLayerEnabled())return[]; return window.BtcDash.chart.overlays.zone?.renderZoneOverlayBatch(buildChannelOverlayItems(timeframe),{layer:"channel",timeframe,source:"Channel",className:"channel-zone-box"})||[];}
  function debugChannelOverlay(timeframe){const ctx=window.BtcDash.state?.channelContexts?.[timeframe], items=buildChannelOverlayItems(timeframe); const binding=window.BtcDash.chart.getChartBindingDiagnostics?.()||{}; const zone=window.BtcDash.chart.overlays.zone?.getLastZoneRenderStats?.()||{}; return {layer:"channel",timeframe,activeTimeframe:binding.activeTimeframe,chartBindingValid:Boolean(binding.hasChart&&binding.hasCandleSeries),contextAvailable:Boolean(ctx?.available),localChannelAvailable:Boolean(ctx?.localChannel?.available),candidateCount:items.length,renderedCount:window.BtcDash.chart.overlayRegistry?.getOverlayCountByLayer?.("channel")||0,skippedCount:items.length?0:1,coordinateFailedCount:zone.coordinateFailedCount||0,skipReasons:items.length?[...(zone.skipReasons||[])]:[ctx?.status||"No Clear Channel"]};}
  window.BtcDash.chart.overlays.channel={renderChannelOverlay,clearChannelOverlay,buildChannelOverlayItems,debugChannelOverlay};
})();
