(function () {
  window.BtcDash = window.BtcDash || {}; window.BtcDash.chart = window.BtcDash.chart || {}; window.BtcDash.chart.overlays = window.BtcDash.chart.overlays || {};
  const bad = new Set(["Broken Liquidity", "Historical Liquidity"]);
  function isLayerEnabled(){const state=window.BtcDash.state;return Boolean(state?.chartRuntime?.layerState?.liquidity||state?.activeLayers?.["EQH/EQL"])}
  function getLiquiditySource(timeframe){const c=window.BtcDash.state?.liquidityContexts?.[timeframe]; const visible=c?.visiblePools||[]; const active=[...(c?.activeBuySidePools||[]),...(c?.activeSellSidePools||[])]; return {context:c,rows:visible.length?visible:active,visibleCount:visible.length,buyCount:(c?.activeBuySidePools||[]).length,sellCount:(c?.activeSellSidePools||[]).length};}
  function buildLiquidityOverlayItems(timeframe){const src=getLiquiditySource(timeframe); if(!src.context?.available)return[]; return src.rows.filter((pool)=>!bad.has(pool.status)).slice(0,6).map((pool)=>({...pool,layer:"liquidity",timeframe,source:"Liquidity",sourceId:pool.id,type:pool.type,label:pool.label||`${timeframe} ${pool.type}`,zoneLow:pool.zoneLow,zoneHigh:pool.zoneHigh,price:pool.centerPrice,startTime:pool.firstSeenTime,endTime:pool.lastTouchTime||pool.lastSeenTime,drawPolicy:pool.drawPolicy||"show"}));}
  function clearLiquidityOverlay(){window.BtcDash.chart.overlays.zone?.clearZoneOverlayLayer?.("liquidity")}
  function renderLiquidityOverlay(timeframe){clearLiquidityOverlay(timeframe); if(!isLayerEnabled())return[]; return window.BtcDash.chart.overlays.zone?.renderZoneOverlayBatch(buildLiquidityOverlayItems(timeframe),{layer:"liquidity",timeframe,source:"Liquidity",className:"liquidity-zone-box"})||[];}
  function debugLiquidityOverlay(timeframe){const src=getLiquiditySource(timeframe), items=buildLiquidityOverlayItems(timeframe); return {layer:"liquidity",timeframe,contextAvailable:Boolean(src.context?.available),visiblePools:src.visibleCount,activeBuySidePools:src.buyCount,activeSellSidePools:src.sellCount,renderedCount:window.BtcDash.chart.overlayRegistry?.getOverlayCountByLayer?.("liquidity")||0,skippedCount:Math.max(0,src.rows.length-items.length),skipReasons:items.length?[]:["No visible liquidity for timeframe"]};}
  window.BtcDash.chart.overlays.liquidity={renderLiquidityOverlay,clearLiquidityOverlay,buildLiquidityOverlayItems,debugLiquidityOverlay};
})();
