(function () {
  window.BtcDash = window.BtcDash || {}; window.BtcDash.engines = window.BtcDash.engines || {};
  const TFS = ["1W", "1D", "4H", "1H"], priority = { "1W": 4, "1D": 3, "4H": 2, "1H": 1 };
  const n = (v) => { const x = Number(v); return Number.isFinite(x) ? x : null; }, tm = (c) => c?.time ?? c?.openTime ?? c?.open_time ?? c?.t ?? null, cfg = (tf) => window.BtcDash.config?.CHANNEL_V2_CONFIG?.[tf] || {}, role = (tf) => cfg(tf).role || (tf === "1W" ? "macro" : tf === "1D" ? "context" : tf === "4H" ? "setup" : "timing");
  const perfCfg = () => window.BtcDash.config?.PERFORMANCE_CONFIG?.channel || {};
  const channelCache = new Map();
  function closed(tf) { return (window.BtcDash.state?.marketData?.[tf] || []).filter((c) => c && c.isRunning !== true && c.isClosed !== false && c.isFinal !== false && c.x !== false && !/running|preview|live/i.test(`${c.source || ""} ${c.status || ""}`)).map((c, i) => ({ ...c, _closedIndex: i })); }
  function atr(candles, idx, len = 14) { let a = []; for (let i = Math.max(1, idx - len + 1); i <= idx; i++) a.push(Math.max(n(candles[i].high)-n(candles[i].low), Math.abs(n(candles[i].high)-n(candles[i-1].close)), Math.abs(n(candles[i].low)-n(candles[i-1].close)))); return a.length ? a.reduce((x,y)=>x+y,0)/a.length : 0; }
  function price(tf) { return n(window.BtcDash.state?.marketData?.[tf]?.at(-1)?.close); } function pct(a,b){return b?Math.abs(a-b)/b*100:999} function scoreLabel(s){return s>=8.5?"Very Strong":s>=7?"Strong":s>=5.5?"Valid":s>=4?"Developing":"Weak"}
  function createEmptyChannelContext(timeframe, reason = "No clear channel detected from valid structural swings.") { return { available: false, timeframe, role: role(timeframe), localChannel: { available: false, type: null, status: "No Clear Channel", score: 0, scoreLabel: "Unavailable", upperLine: null, midLine: null, lowerLine: null, upperZone: null, midZone: null, lowerZone: null, anchors: [], touches: null, fitMetrics: null, validFromTime: null, validToTime: null, projectionEndTime: null, isActive: false, isBroken: false, brokenAt: null, breakDirection: null, retestStatus: null, nearestBoundary: null, summary: reason }, projectedChannels: [], historicalChannels: [], nearestBoundary: null, marketZoneRows: [], debugStats: {}, summary: "No Clear Channel", status: "No Clear Channel" }; }
  function getChannelSourceSwings(timeframe) { const layer = cfg(timeframe).sourceSwingLayer || (timeframe === "1W" || timeframe === "1D" ? "major" : "internal"); const swings = window.BtcDash.engines.structure?.getStructuralSourceSwings?.(timeframe, layer) || []; return swings.filter((s) => s?.structureType !== "rawPivot" && s?.layer !== "rawPivot").slice(-(perfCfg().maxSourceSwings?.[timeframe] || swings.length)); }
  function calculateLineByTwoPoints(a,b){const dx=(n(b.index)-n(a.index))||1,slope=(n(b.price)-n(a.price))/dx,intercept=n(a.price)-slope*n(a.index);return{ slope, intercept, startIndex:n(a.index), endIndex:n(b.index), startTime:a.time, endTime:b.time }}
  function valueAtLine(line,index){return line.slope*index+line.intercept}
  function buildChannelCandidates(swings,candles,timeframe){const c=cfg(timeframe), highs=swings.filter(s=>s.type==='high'), lows=swings.filter(s=>s.type==='low'); if(swings.length<(c.minAnchorSwings||4)||highs.length<2||lows.length<2)return[]; const h1=highs.at(-2),h2=highs.at(-1),l1=lows.at(-2),l2=lows.at(-1); const upperLine=calculateLineByTwoPoints(h1,h2), lowerLine=calculateLineByTwoPoints(l1,l2); const midLine={...upperLine,slope:(upperLine.slope+lowerLine.slope)/2,intercept:(upperLine.intercept+lowerLine.intercept)/2}; const end=Math.max(h2.index,l2.index); const width=Math.abs(valueAtLine(upperLine,end)-valueAtLine(lowerLine,end)), mid=(valueAtLine(upperLine,end)+valueAtLine(lowerLine,end))/2, widthPct=width/mid*100; if(widthPct>(c.maxChannelWidthPct||30)||width<atr(candles,end)*(c.minChannelWidthAtr||1))return[]; return[{type:upperLine.slope>0?'Ascending Channel':upperLine.slope<0?'Descending Channel':'Range Channel',upperLine,lowerLine,midLine,anchors:[h1,h2,l1,l2],candidateStartIndex:Math.min(h1.index,l1.index),candidateEndIndex:end,width,widthPct,direction:upperLine.slope>0?'up':upperLine.slope<0?'down':'range',note:'Candidate from structural swings.'}];}
  function validateChannelCandidate(ch,swings,candles,timeframe){const c=cfg(timeframe), tol=atr(candles,ch.candidateEndIndex,c.atrLength||14)*(c.toleranceAtrMultiplier||.5); const touches={upper:[],lower:[],mid:[]}; swings.forEach(s=>{const u=valueAtLine(ch.upperLine,s.index),l=valueAtLine(ch.lowerLine,s.index),m=valueAtLine(ch.midLine,s.index); if(Math.abs(s.price-u)<=tol)touches.upper.push(s); if(Math.abs(s.price-l)<=tol)touches.lower.push(s); if(Math.abs(s.price-m)<=tol)touches.mid.push(s);}); const total=touches.upper.length+touches.lower.length; const inlierRatio=swings.length?total/swings.length:0; const valid=total>=(c.minTouchesTotal||3)&&Math.max(touches.upper.length,touches.lower.length)>=(c.minTouchesMainSide||2)&&inlierRatio>=(c.minInlierRatio||.4); ch.touches=touches; ch.fitMetrics={touchCount:total,inlierRatio,fitErrorAtr:0,tolerance:tol}; ch.isValid=valid; ch.rejectionReason=valid?null:'Insufficient multi-touch channel validation.'; return ch;}
  function buildChannelZones(ch,candles,timeframe){const c=cfg(timeframe), i=candles.length-1, tol=Math.max(atr(candles,i,c.atrLength||14)*(c.toleranceAtrMultiplier||.5), valueAtLine(ch.midLine,i)*(c.nearBoundaryPct||1)/100); ['upper','mid','lower'].forEach(k=>{const line=ch[`${k}Line`], center=valueAtLine(line,i); ch[`${k}Zone`]={centerPrice:center,zoneLow:center-tol,zoneHigh:center+tol,tolerance:tol,sourceLine:line,boundaryType:k};}); return ch;}
  function deriveChannelStatus(ch,candles,timeframe){const c=cfg(timeframe), last=candles.at(-1), close=n(last.close), high=n(last.high), low=n(last.low); let status='Inside Channel', broken=false, dir=null; if(close>ch.upperZone.zoneHigh*(1+(c.breakBufferPct||.1)/100)){status='Broken Up';broken=true;dir='up'} else if(close<ch.lowerZone.zoneLow*(1-(c.breakBufferPct||.1)/100)){status='Broken Down';broken=true;dir='down'} else if(high>ch.upperZone.zoneHigh&&close<=ch.upperZone.zoneHigh)status='Sweep Upper'; else if(low<ch.lowerZone.zoneLow&&close>=ch.lowerZone.zoneLow)status='Sweep Lower'; else { const d=[ch.upperZone,ch.midZone,ch.lowerZone].map(z=>({z,d:pct(close,z.centerPrice)})).sort((a,b)=>a.d-b.d)[0]; status=d.z.boundaryType==='upper'?'Near Upper':d.z.boundaryType==='lower'?'Near Lower':'Near Midline'; } ch.status=status; ch.isBroken=broken; ch.breakDirection=dir; ch.brokenAt=broken?tm(last):null; ch.isActive=!broken; ch.retestStatus=broken?'Needs Retest':'Inside/near channel'; return ch;}
  function deriveNearestChannelBoundary(ch,currentPrice,timeframe){if(!ch?.available&&!ch?.upperZone)return null; return [ch.upperZone,ch.midZone,ch.lowerZone].filter(Boolean).map(z=>({boundaryType:z.boundaryType,zoneLow:z.zoneLow,zoneHigh:z.zoneHigh,centerPrice:z.centerPrice,distancePct:pct(currentPrice,z.centerPrice),relationToPrice:z.centerPrice>currentPrice?'above_price':z.centerPrice<currentPrice?'below_price':'at_price',label:`Channel ${z.boundaryType}`})).sort((a,b)=>a.distancePct-b.distancePct)[0]||null;}
  function scoreChannel(ch,timeframe){const c=cfg(timeframe), fit=ch.fitMetrics||{}; const s=Math.max(0,Math.min(10,priority[timeframe]*.8+(fit.touchCount||0)*.9+(fit.inlierRatio||0)*3+(ch.isBroken?-1:1))); ch.score=Number(s.toFixed(2)); ch.scoreLabel=scoreLabel(ch.score); ch.drawPolicy=ch.score>=(c.minScoreToDisplay||5)&&!ch.isBroken?'show':'summaryOnly'; return ch;}
  function buildChannelMarketZoneRows(context,timeframe){const ch=context.localChannel;if(!ch?.available||ch.status==='No Clear Channel')return[];return [ch.upperZone,ch.lowerZone,ch.midZone,context.nearestBoundary].filter(Boolean).slice(0,4).map((z,i)=>({id:`channel-row-${timeframe}-${z.boundaryType||i}`,timeframe,source:'Channel',type:z.boundaryType==='upper'?'Channel Upper':z.boundaryType==='lower'?'Channel Lower':'Channel Midline',status:ch.status,boundaryType:z.boundaryType,zoneLow:z.zoneLow,zoneHigh:z.zoneHigh,centerPrice:z.centerPrice,relationToPrice:z.relationToPrice||'reference',distancePct:z.distancePct??0,score:ch.score,scoreLabel:ch.scoreLabel,sourceTags:['Channel',z.boundaryType,timeframe],drawPolicy:ch.drawPolicy,label:`${timeframe} Channel ${z.boundaryType}`,note:'Planning context only.'}));}
  function rebuildChannelForTimeframe(timeframe){const started=performance.now(); try{const candles=closed(timeframe), swings=getChannelSourceSwings(timeframe), c=cfg(timeframe); const cacheKey = `${timeframe}:${swings.map(s=>`${s.id||s.time}-${s.price}`).join("|")}:${candles.at(-1)?.open_time||candles.at(-1)?.time||""}:${candles.at(-1)?.close||""}`; if(channelCache.has(cacheKey)) { const cached = channelCache.get(cacheKey); window.BtcDash.state.channelContexts[timeframe]=cached; return cached; } if(candles.length<20||swings.length<(c.minAnchorSwings||4)){const e=createEmptyChannelContext(timeframe); window.BtcDash.state.channelContexts[timeframe]=e; return e;} const candidates=buildChannelCandidates(swings,candles,timeframe).map(ch=>scoreChannel(deriveChannelStatus(buildChannelZones(validateChannelCandidate(ch,swings,candles,timeframe),candles,timeframe),candles,timeframe),timeframe)); const valid=candidates.filter(ch=>ch.isValid&&ch.score>=(c.minScoreToDisplay||5)&&!ch.isBroken).sort((a,b)=>b.score-a.score); if(!valid.length){const e=createEmptyChannelContext(timeframe); e.debugStats={candidateChannelCount:candidates.length, sourceSwingCount: swings.length, quickRejectedCount: Math.max(0, candidates.length-valid.length), validatedCount: candidates.length, rejectedRawPivotCount:0, durationMs:Number((performance.now()-started).toFixed(1))}; window.BtcDash.state.channelContexts[timeframe]=e; channelCache.set(cacheKey,e); return e;} const best=valid[0]; best.available=true; best.validFromTime=tm(candles[best.candidateStartIndex]); best.validToTime=tm(candles.at(-1)); best.projectionEndTime=tm(candles.at(-1)); best.nearestBoundary=deriveNearestChannelBoundary(best,price(timeframe),timeframe); best.summary=`${timeframe} ${best.type}: ${best.status}.`; const context={available:true,timeframe,role:role(timeframe),localChannel:best,projectedChannels:[],historicalChannels:candidates.filter(ch=>ch!==best).slice(0,c.maxHistoricalChannels||3),nearestBoundary:best.nearestBoundary,marketZoneRows:[],debugStats:{candidateChannelCount:candidates.length, sourceSwingCount: swings.length, quickRejectedCount: Math.max(0, candidates.length-valid.length), validatedCount: candidates.length, selectedChannelScore: best.score, activeChannelCount:1, durationMs:Number((performance.now()-started).toFixed(1))},summary:best.summary,status:best.status}; context.marketZoneRows=buildChannelMarketZoneRows(context,timeframe); window.BtcDash.state.channelContexts[timeframe]=context; channelCache.set(cacheKey, context); try{channelContexts[timeframe]=context}catch(e){} return context;}catch(error){const e=createEmptyChannelContext(timeframe,`Channel V2 error: ${error.message}`); window.BtcDash.state.channelContexts[timeframe]=e; return e;}}
  function rebuildChannelContexts(){const contexts={};TFS.forEach(tf=>contexts[tf]=rebuildChannelForTimeframe(tf));const st=Object.values(contexts).reduce((a,c)=>({candidateChannelCount:a.candidateChannelCount+(c.debugStats?.candidateChannelCount||0),activeChannelCount:a.activeChannelCount+(c.available?1:0),historicalChannelCount:a.historicalChannelCount+(c.historicalChannels?.length||0),projectedChannelCount:a.projectedChannelCount+(c.projectedChannels?.length||0),noClearChannelCount:a.noClearChannelCount+(c.available?0:1),rejectedRawPivotCount:a.rejectedRawPivotCount,marketZoneRowCount:a.marketZoneRowCount+(c.marketZoneRows?.length||0)}),{candidateChannelCount:0,activeChannelCount:0,historicalChannelCount:0,projectedChannelCount:0,noClearChannelCount:0,rejectedRawPivotCount:0,marketZoneRowCount:0});window.BtcDash.state.channelDebugStats={...(window.BtcDash.state.channelDebugStats||{}),...st,lastBuildAt:new Date().toISOString(),warnings:[]};return contexts;}
  function getChannelContext(tf){return window.BtcDash.state?.channelContexts?.[tf]||createEmptyChannelContext(tf)}
  const api={rebuildChannelContexts,rebuildChannelForTimeframe,createEmptyChannelContext,getChannelSourceSwings,buildChannelCandidates,validateChannelCandidate,deriveChannelStatus,scoreChannel,buildChannelMarketZoneRows,getChannelContext,calculateLineByTwoPoints,valueAtLine,deriveNearestChannelBoundary,rebuildAllChannelContexts:rebuildChannelContexts,buildChannelContext:rebuildChannelForTimeframe};
  window.BtcDash.engines.channel=api;window.BtcDash.channelEngine=api;window.rebuildChannelContexts=rebuildChannelContexts;window.rebuildAllChannelContexts=rebuildChannelContexts;
})();
