(function () {
  window.BtcDash = window.BtcDash || {};
  window.BtcDash.engines = window.BtcDash.engines || {};
  const TFS = ["1W", "1D", "4H", "1H"];
  const priority = { "1W": 4, "1D": 3, "4H": 2, "1H": 1 };
  const n = (v) => { const x = Number(v); return Number.isFinite(x) ? x : null; };
  const tm = (c) => c?.time ?? c?.openTime ?? c?.open_time ?? c?.t ?? null;
  const cfg = (tf) => window.BtcDash.config?.SR_V2_CONFIG?.[tf] || {};
  const role = (tf) => cfg(tf).role || (tf === "1W" ? "macro" : tf === "1D" ? "context" : tf === "4H" ? "setup" : "timing");
  function closed(timeframe) { return (window.BtcDash.state?.marketData?.[timeframe] || []).filter((c) => c && c.isRunning !== true && c.isClosed !== false && c.isFinal !== false && c.x !== false && !/running|preview|live/i.test(`${c.source || ""} ${c.status || ""}`)).map((c, i) => ({ ...c, _closedIndex: i })); }
  function atr(candles, index, length = 14) { const from = Math.max(1, index - length + 1); const trs = []; for (let i = from; i <= index; i += 1) { const h = n(candles[i]?.high), l = n(candles[i]?.low), pc = n(candles[i - 1]?.close); if (h == null || l == null || pc == null) continue; trs.push(Math.max(h - l, Math.abs(h - pc), Math.abs(l - pc))); } return trs.length ? trs.reduce((a, b) => a + b, 0) / trs.length : 0; }
  function currentPrice(tf) { return n(window.BtcDash.state?.marketData?.[tf]?.at(-1)?.close); }
  function dist(center, tf) { const price = currentPrice(tf); return price ? Math.abs(center - price) / price * 100 : 999; }
  function rel(center, tf) { const price = currentPrice(tf); if (!price) return "unknown"; return center > price ? "above_price" : center < price ? "below_price" : "at_price"; }
  function scoreLabel(score) { return score >= 8.5 ? "Very Strong" : score >= 7 ? "Strong" : score >= 5.5 ? "Valid" : score >= 4 ? "Developing" : "Weak"; }
  function createEmptySrContext(timeframe, reason = "No valid S/R zones detected from structural swings.") { return { available: false, timeframe, role: role(timeframe), rawLevels: [], zoneClusters: [], zones: [], activeSupports: [], activeResistances: [], currentReactionZones: [], brokenZones: [], flippedZones: [], sweptZones: [], historicalZones: [], projectedZones: [], nearestSupport: null, nearestResistance: null, strongestSupport: null, strongestResistance: null, visibleZones: [], marketZoneRows: [], debugStats: {}, summary: reason, status: "No Clear S/R", supportZones: [], resistanceZones: [] }; }
  function getSrSourceSwings(timeframe) { const layer = cfg(timeframe).sourceSwingLayer || (timeframe === "1W" || timeframe === "1D" ? "major" : "internal"); return window.BtcDash.engines.structure?.getStructuralSourceSwings?.(timeframe, layer) || []; }
  function buildRawSrLevelsFromSwings(swings, candles, timeframe) { const c = cfg(timeframe); return swings.map((swing) => { const price = n(swing.price); const i = n(swing.index) || 0; const tolerance = Math.max(price * ((c.zonePctTolerance || 0.5) / 100), atr(candles, i, c.atrLength || 14) * (c.zoneAtrMultiplier || 0.5)); return { id: `${timeframe}-sr-raw-${swing.id || i}`, timeframe, type: swing.type === "low" ? "support" : "resistance", price, time: swing.time, index: i, sourceSwing: swing, sourceLabel: swing.label, layer: swing.layer, atr: atr(candles, i, c.atrLength || 14), tolerance, zoneLow: price - tolerance, zoneHigh: price + tolerance, ageBars: Math.max(0, candles.length - 1 - i) }; }).filter((level) => Number.isFinite(level.price)); }
  function clusterSrLevels(rawLevels, candles, timeframe) { const c = cfg(timeframe); const byType = ["support", "resistance"].flatMap((type) => { const levels = rawLevels.filter((l) => l.type === type).sort((a, b) => a.price - b.price); const clusters = []; levels.forEach((level) => { const merge = level.price * ((c.mergePctTolerance || 0.5) / 100); let cluster = clusters.find((z) => level.zoneLow <= z.zoneHigh + merge && level.zoneHigh >= z.zoneLow - merge); if (!cluster) { cluster = { id: `${timeframe}-sr-cluster-${type}-${clusters.length}`, timeframe, source: "S/R", candidateType: "Fresh Structural Zone", originalType: type, activeType: type, status: "Fresh Structural Zone", centerPrice: level.price, zoneLow: level.zoneLow, zoneHigh: level.zoneHigh, tolerance: level.tolerance, sourceSwings: [], sourceSwingCount: 0, sourceLabels: [], touches: [], touchCount: 0, firstSeenTime: level.time, lastTouchTime: level.time, lastReactionTime: null, ageBars: level.ageBars, recencyScore: 0, relationToPrice: rel(level.price, timeframe), distancePct: 0, breakState: { isBroken: false, breakDirection: null, brokenAt: null, brokenByClose: false, closeCountBeyondZone: 0, sweepOnly: false, weakBreak: false, confirmation: "None", note: "No close break." }, flipState: { isFlipped: false, fromType: null, toType: null, retestConfirmed: false, retestTime: null, reclaimFailed: false, note: "No flip." }, reactionState: { lastReaction: null, reactionStrength: 0, bounceCount: 0, rejectionCount: 0, sweepCount: 0, closeRespectCount: 0, note: "No reaction." }, score: 0, scoreLabel: "Weak", scoreFactors: [], riskFlags: [], htfSources: [timeframe], confluenceSources: [], drawPolicy: "show", label: `${timeframe} ${type === "support" ? "Support" : "Resistance"}`, note: "Planning context only." }; clusters.push(cluster); } cluster.zoneLow = Math.min(cluster.zoneLow, level.zoneLow); cluster.zoneHigh = Math.max(cluster.zoneHigh, level.zoneHigh); cluster.centerPrice = (cluster.zoneLow + cluster.zoneHigh) / 2; cluster.sourceSwings.push(level.sourceSwing); cluster.sourceSwingCount = cluster.sourceSwings.length; cluster.sourceLabels = [...new Set(cluster.sourceSwings.map((s) => s.label).filter(Boolean))]; cluster.firstSeenTime = cluster.sourceSwings[0]?.time || cluster.firstSeenTime; cluster.lastTouchTime = level.time; cluster.ageBars = Math.min(cluster.ageBars, level.ageBars); }); return clusters; }); return byType; }
  function deriveSrZoneStatus(zone, candles, timeframe) { const c = cfg(timeframe); const out = { ...zone, touches: [], sourceSwings: [...zone.sourceSwings] }; let closeBeyond = 0; for (let i = Math.max(...out.sourceSwings.map((s) => n(s.index) || 0)) + 1; i < candles.length; i += 1) { const high = n(candles[i].high), low = n(candles[i].low), close = n(candles[i].close); if (high == null || low == null || close == null) continue; const touched = high >= out.zoneLow && low <= out.zoneHigh; if (touched) { out.touches.push({ time: tm(candles[i]), index: i, close }); out.lastTouchTime = tm(candles[i]); }
      const supportBreak = out.originalType === "support" && close < out.zoneLow * (1 - (c.breakBufferPct || 0.1) / 100); const resistanceBreak = out.originalType === "resistance" && close > out.zoneHigh * (1 + (c.breakBufferPct || 0.1) / 100); const supportWeak = out.originalType === "support" && close < out.zoneLow * (1 - (c.weakBreakBufferPct || 0.04) / 100); const resistanceWeak = out.originalType === "resistance" && close > out.zoneHigh * (1 + (c.weakBreakBufferPct || 0.04) / 100); const supportSweep = out.originalType === "support" && low < out.zoneLow && close >= out.zoneLow; const resistanceSweep = out.originalType === "resistance" && high > out.zoneHigh && close <= out.zoneHigh; if (supportSweep || resistanceSweep) { out.status = "Swept Zone"; out.candidateType = "Swept Zone"; out.breakState.sweepOnly = true; out.reactionState.sweepCount += 1; }
      if (supportWeak || resistanceWeak) { out.status = "Weak Break / Needs Confirmation"; out.breakState.weakBreak = true; out.breakState.confirmation = "Needs Confirmation"; }
      if (supportBreak || resistanceBreak) closeBeyond += 1; else closeBeyond = 0; if (closeBeyond >= (c.confirmationCloseCount || 1)) { out.status = "Broken Zone"; out.candidateType = "Broken Zone"; out.breakState = { ...out.breakState, isBroken: true, brokenByClose: true, breakDirection: supportBreak ? "down" : "up", brokenAt: tm(candles[i]), closeCountBeyondZone: closeBeyond, confirmation: "Close Confirmed", note: "Close-confirmed break beyond structural S/R zone." }; out.activeType = out.originalType === "support" ? "resistance" : "support"; }
      if (out.breakState.isBroken && touched) { out.status = "Flip Zone"; out.candidateType = "Flip Zone"; out.flipState = { isFlipped: true, fromType: out.originalType, toType: out.activeType, retestConfirmed: true, retestTime: tm(candles[i]), reclaimFailed: false, note: "Broken zone retested as flipped reference." }; break; }
    } out.touchCount = out.touches.length; out.distancePct = dist(out.centerPrice, timeframe); out.relationToPrice = rel(out.centerPrice, timeframe); if (!out.breakState.isBroken && out.touchCount >= (c.minTouchesForConfirmedZone || 2)) { out.status = out.status === "Fresh Structural Zone" ? "Confirmed Reaction Zone" : out.status; out.candidateType = out.status; out.reactionState.closeRespectCount = out.touchCount; } if (out.ageBars > (c.maxZoneAgeBars || 999) && out.status !== "Flip Zone") { out.status = "Historical Reaction Zone"; out.candidateType = "Historical Reaction Zone"; } return out; }
  function scoreSrZone(zone, timeframe) { const c = cfg(timeframe); const recency = Math.max(0, 2 - zone.ageBars / (c.recencyHalfLifeBars || 100)); const distanceScore = Math.max(0, 2 - zone.distancePct / 5); const statusBonus = zone.status === "Flip Zone" ? 1.8 : zone.status === "Confirmed Reaction Zone" ? 1.2 : zone.status === "Swept Zone" ? 0.7 : zone.status === "Broken Zone" ? -1 : 0; const score = Math.max(0, Math.min(10, zone.sourceSwingCount * 1.2 + zone.touchCount * 0.5 + priority[timeframe] * 0.7 + recency + distanceScore + statusBonus)); zone.score = Number(score.toFixed(2)); zone.scoreLabel = scoreLabel(zone.score); zone.scoreFactors = ["structural-swings", "touches", "timeframe-priority", "recency", "distance", zone.status]; zone.drawPolicy = zone.score >= (c.minScoreToDisplay || 4) && !["Broken Zone", "Historical Reaction Zone"].includes(zone.status) ? "show" : "summaryOnly"; return zone; }
  function buildSrMarketZoneRows(context, timeframe) { const rows = [context.nearestSupport, context.nearestResistance, context.strongestSupport, context.strongestResistance, ...(context.currentReactionZones || []), ...(context.flippedZones || [])].filter(Boolean); const seen = new Set(); return rows.filter((z) => z.score >= (cfg(timeframe).minScoreForMarketZone || 5) || z === context.nearestSupport || z === context.nearestResistance).filter((z) => { const key = `${z.activeType}-${Math.round(z.zoneLow)}-${Math.round(z.zoneHigh)}`; if (seen.has(key)) return false; seen.add(key); return !["Broken Zone", "Historical Reaction Zone"].includes(z.status); }).slice(0, 8).map((z) => ({ id: `sr-row-${z.id}`, timeframe, source: "S/R", type: z.activeType === "support" ? "Support" : z.activeType === "resistance" ? "Resistance" : "Current Reaction", status: z.status, activeType: z.activeType, zoneLow: z.zoneLow, zoneHigh: z.zoneHigh, centerPrice: z.centerPrice, relationToPrice: z.relationToPrice, distancePct: z.distancePct, score: z.score, scoreLabel: z.scoreLabel, sourceTags: ["S/R", z.activeType, timeframe], drawPolicy: z.drawPolicy, label: z.label, note: "Reference only." })); }
  function rebuildSrForTimeframe(timeframe) { try { const candles = closed(timeframe); const swings = getSrSourceSwings(timeframe); if (candles.length < 20 || !swings.length) { const empty = createEmptySrContext(timeframe, "Reliable structural swings unavailable for S/R zones."); window.BtcDash.state.srContexts[timeframe] = empty; return empty; } const rawLevels = buildRawSrLevelsFromSwings(swings, candles, timeframe); const zoneClusters = clusterSrLevels(rawLevels, candles, timeframe); const zones = zoneClusters.map((z) => scoreSrZone(deriveSrZoneStatus(z, candles, timeframe), timeframe)); const activeSupports = zones.filter((z) => z.activeType === "support" && !z.breakState.isBroken && z.status !== "Historical Reaction Zone").sort((a, b) => b.score - a.score).slice(0, cfg(timeframe).maxActiveSupport || 3); const activeResistances = zones.filter((z) => z.activeType === "resistance" && !z.breakState.isBroken && z.status !== "Historical Reaction Zone").sort((a, b) => b.score - a.score).slice(0, cfg(timeframe).maxActiveResistance || 3); const context = { available: zones.length > 0, timeframe, role: role(timeframe), rawLevels, zoneClusters, zones, activeSupports, activeResistances, currentReactionZones: zones.filter((z) => z.touchCount && z.distancePct < (cfg(timeframe).retestTolerancePct || 1)).slice(0, 2), brokenZones: zones.filter((z) => z.status === "Broken Zone"), flippedZones: zones.filter((z) => z.status === "Flip Zone"), sweptZones: zones.filter((z) => z.status === "Swept Zone"), historicalZones: zones.filter((z) => z.status === "Historical Reaction Zone"), projectedZones: [], nearestSupport: activeSupports.sort((a, b) => a.distancePct - b.distancePct)[0] || null, nearestResistance: activeResistances.sort((a, b) => a.distancePct - b.distancePct)[0] || null, strongestSupport: activeSupports.sort((a, b) => b.score - a.score)[0] || null, strongestResistance: activeResistances.sort((a, b) => b.score - a.score)[0] || null, visibleZones: [...activeSupports, ...activeResistances].filter((z) => z.drawPolicy === "show").slice(0, 6), marketZoneRows: [], debugStats: { sourceSwingCount: swings.length, rawLevelCount: rawLevels.length, zoneClusterCount: zoneClusters.length }, summary: zones.length ? `${timeframe} S/R zones built from structural swings.` : "No valid S/R zones detected from structural swings.", status: zones.length ? "S/R Context Ready" : "No Clear S/R", supportZones: activeSupports, resistanceZones: activeResistances }; context.marketZoneRows = buildSrMarketZoneRows(context, timeframe); window.BtcDash.state.srContexts[timeframe] = context; try { srContexts[timeframe] = context; } catch (e) {} return context; } catch (error) { const empty = createEmptySrContext(timeframe, `S/R V2.1 error: ${error.message}`); window.BtcDash.state.srContexts[timeframe] = empty; return empty; } }
  function rebuildSrContexts() { const contexts = {}; TFS.forEach((tf) => { contexts[tf] = rebuildSrForTimeframe(tf); }); const stats = Object.values(contexts).reduce((a, c) => ({ rawLevelCount: a.rawLevelCount + (c.rawLevels?.length || 0), zoneClusterCount: a.zoneClusterCount + (c.zoneClusters?.length || 0), activeSupportCount: a.activeSupportCount + (c.activeSupports?.length || 0), activeResistanceCount: a.activeResistanceCount + (c.activeResistances?.length || 0), brokenZoneCount: a.brokenZoneCount + (c.brokenZones?.length || 0), flippedZoneCount: a.flippedZoneCount + (c.flippedZones?.length || 0), sweptZoneCount: a.sweptZoneCount + (c.sweptZones?.length || 0), historicalZoneCount: a.historicalZoneCount + (c.historicalZones?.length || 0), marketZoneRowCount: a.marketZoneRowCount + (c.marketZoneRows?.length || 0) }), { rawLevelCount: 0, zoneClusterCount: 0, activeSupportCount: 0, activeResistanceCount: 0, brokenZoneCount: 0, flippedZoneCount: 0, sweptZoneCount: 0, historicalZoneCount: 0, marketZoneRowCount: 0 }); window.BtcDash.state.srDebugStats = { ...(window.BtcDash.state.srDebugStats || {}), ...stats, lastBuildAt: new Date().toISOString(), warnings: [] }; return contexts; }
  function getSrContext(timeframe) { return window.BtcDash.state?.srContexts?.[timeframe] || createEmptySrContext(timeframe); }
  const api = { rebuildSrContexts, rebuildSrForTimeframe, createEmptySrContext, getSrSourceSwings, buildRawSrLevelsFromSwings, clusterSrLevels, deriveSrZoneStatus, scoreSrZone, buildSrMarketZoneRows, getSrContext, rebuildAllSrContexts: rebuildSrContexts, buildSrContext: rebuildSrForTimeframe, clusterSrLevelsIntoZones: clusterSrLevels };
  window.BtcDash.engines.sr = api; window.BtcDash.srEngine = api; window.rebuildSrContexts = rebuildSrContexts; window.rebuildAllSrContexts = rebuildSrContexts;
})();
